-- Migration 0031: Add all thinning mechanism fields
BEGIN;
ALTER TABLE "dashboard_component" ADD COLUMN "acid_water_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "acid_water_dissolved_o2_ppm" numeric(8, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "alkaline_water_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "alkaline_water_velocity_fps" numeric(8, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "amine_acid_gas_loading" numeric(6, 3) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "amine_concentration_wt_percent" numeric(6, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "amine_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "amine_type" varchar(10) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "h2so4_concentration_wt_percent" numeric(6, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "h2so4_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "h2so4_velocity_fps" numeric(8, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "hcl_concentration_wt_percent" numeric(6, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "hcl_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "hcl_velocity_fps" numeric(8, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "hf_concentration_wt_percent" numeric(6, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "hf_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "hf_velocity_fps" numeric(8, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "ht_h2_partial_pressure_psia" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "ht_h2s_h2_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "ht_h2s_partial_pressure_psia" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "soil_cathodic_protection" boolean DEFAULT false NOT NULL;
ALTER TABLE "dashboard_component" ALTER COLUMN "soil_cathodic_protection" DROP DEFAULT;
ALTER TABLE "dashboard_component" ADD COLUMN "soil_coating_condition" varchar(10) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "soil_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "soil_resistivity_ohm_cm" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "sulfidic_corrosion_rate_mpy" numeric(10, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "sulfidic_sulfur_wt_percent" numeric(6, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "sulfidic_tan" numeric(6, 2) NULL;
ALTER TABLE "dashboard_component" ADD COLUMN "sulfidic_velocity_fps" numeric(8, 2) NULL;
COMMIT;
