# Generated by Django 6.0.1 on 2026-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=255, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
