# Generated by Django 6.0.1 on 2026-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_facility_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
