# Generated by Django 6.0.1 on 2026-01-18 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('plant_equipment_type', models.CharField(max_length=255, verbose_name='Plant Equipment Type')),
                ('plant_equipment_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plant Equipment Description')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.system')),
            ],
        ),
    ]
