# Generated by Django 6.0.1 on 2026-01-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbix_equipment_type', models.CharField(max_length=255, verbose_name='RBIX Equipment Type')),
                ('rbix_component_type', models.CharField(max_length=255, verbose_name='RBIX Component Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('p_and_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='P&ID')),
                ('p_and_id_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='P&ID Other')),
                ('other_drawings', models.CharField(blank=True, max_length=255, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('rbi_calculation_date', models.DateField(blank=True, null=True, verbose_name='RBI Calculation Date')),
                ('design_life_years', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Design Life (years)')),
                ('component_life_years', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Component Life (years)')),
                ('remaining_life_years', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remaining Life (years)')),
                ('external_coating_date', models.DateField(blank=True, null=True, verbose_name='External Coating Installation Date')),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_pipe_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rep. Pipe No.')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipment')),
            ],
        ),
    ]
