# Generated by Django 6.0.1 on 2026-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='atm_pressure_liquid',
            field=models.DecimalField(blank=True, decimal_places=2, default=14.7, max_digits=10, null=True, verbose_name='Atm. Pressure (psi)'),
        ),
        migrations.AddField(
            model_name='component',
            name='atm_pressure_vapor',
            field=models.DecimalField(blank=True, decimal_places=2, default=14.7, max_digits=10, null=True, verbose_name='Atm. Pressure (psi)'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Component Diameter (inches)'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Component Mass (lb)'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type_table',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Component Type (Table 3.1)'),
        ),
        migrations.AddField(
            model_name='component',
            name='conversion_factor_c2',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, verbose_name='Conversion Factor (C2)'),
        ),
        migrations.AddField(
            model_name='component',
            name='cost_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True, verbose_name='Cost Factor'),
        ),
        migrations.AddField(
            model_name='component',
            name='detection_class',
            field=models.CharField(blank=True, choices=[('A', 'A - Instrumentation (Auto)'), ('B', 'B - Detectors (Remote)'), ('C', 'C - Visual / Marginal')], max_length=10, null=True, verbose_name='Detection Classification'),
        ),
        migrations.AddField(
            model_name='component',
            name='discharge_coeff_liquid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.61, max_digits=5, null=True, verbose_name='Discharge Coeff. (Cd)'),
        ),
        migrations.AddField(
            model_name='component',
            name='discharge_coeff_vapor',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True, verbose_name='Discharge Coeff. (Cd)'),
        ),
        migrations.AddField(
            model_name='component',
            name='environmental_cost_per_bbl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Environmental Cost ($/bbl)'),
        ),
        migrations.AddField(
            model_name='component',
            name='equipment_cost_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Equipment Cost ($/ft²)'),
        ),
        migrations.AddField(
            model_name='component',
            name='fluid_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Temperature (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='injury_cost_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Injury Cost ($/person)'),
        ),
        migrations.AddField(
            model_name='component',
            name='inventory_group_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Inventory Group Mass (lb)'),
        ),
        migrations.AddField(
            model_name='component',
            name='isolation_class',
            field=models.CharField(blank=True, choices=[('A', 'A - Auto Isolation'), ('B', 'B - Remote Manual'), ('C', 'C - Manual Valves')], max_length=10, null=True, verbose_name='Isolation Classification'),
        ),
        migrations.AddField(
            model_name='component',
            name='material_construction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material of Construction'),
        ),
        migrations.AddField(
            model_name='component',
            name='mitigation_system',
            field=models.CharField(blank=True, choices=[('None', 'None/No Mitigation (0%)'), ('InventoryBlowdown', 'Inventory blowdown, coupled with isolation system (25%)'), ('FireWaterDeluge', 'Fire water deluge system and monitors (20%)'), ('FireWaterMonitors', 'Fire water monitors only (5%)'), ('FoamSpray', 'Foam spray system (15%)')], max_length=100, null=True, verbose_name='Mitigation System'),
        ),
        migrations.AddField(
            model_name='component',
            name='outage_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True, verbose_name='Outage Multiplier'),
        ),
        migrations.AddField(
            model_name='component',
            name='personnel_maintenance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Personnel Maintenance'),
        ),
        migrations.AddField(
            model_name='component',
            name='personnel_shift_1',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Personnel Shift 1'),
        ),
        migrations.AddField(
            model_name='component',
            name='personnel_shift_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Personnel Shift 2'),
        ),
        migrations.AddField(
            model_name='component',
            name='production_cost_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Production Cost ($/day)'),
        ),
        migrations.AddField(
            model_name='component',
            name='representative_fluid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Representative Fluid'),
        ),
        migrations.AddField(
            model_name='component',
            name='storage_pressure_liquid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Storage Pressure Ps (psia)'),
        ),
        migrations.AddField(
            model_name='component',
            name='storage_pressure_vapor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Storage Pressure Ps (psia)'),
        ),
        migrations.AddField(
            model_name='component',
            name='stored_phase',
            field=models.CharField(blank=True, choices=[('Liquid', 'Liquid'), ('Vapor', 'Vapor / Gas')], max_length=50, null=True, verbose_name='Stored Phase'),
        ),
        migrations.AddField(
            model_name='component',
            name='time_present_maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Time Present Maintenance (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='time_present_shift_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True, verbose_name='Time Present Shift 1 (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='time_present_shift_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Time Present Shift 2 (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='toxic_mass_fraction',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True, verbose_name='Toxic Mass Fraction'),
        ),
        migrations.AddField(
            model_name='component',
            name='unit_area_safety',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=15, null=True, verbose_name='Unit Area (ft²)'),
        ),
        migrations.AddField(
            model_name='component',
            name='viscosity_correction',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True, verbose_name='Viscosity Correction (Kvn)'),
        ),
    ]
