# Generated by Django 6.0.1 on 2026-01-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_component_representative_fluid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_type_table',
        ),
        migrations.AlterField(
            model_name='component',
            name='rbix_component_type',
            field=models.CharField(choices=[('COMPC', 'Compressor - Centrifugal (COMPC)'), ('COMPR', 'Compressor - Reciprocating (COMPR)'), ('HEXSS, HEXTS', 'Heat Exchanger (HEXSS, HEXTS)'), ('PIPE-1, PIPE-2', 'Pipe - 1, 2 inch (PIPE-1, PIPE-2)'), ('PIPE-4, PIPE-6', 'Pipe - 4, 6 inch (PIPE-4, PIPE-6)'), ('PIPE-8+', 'Pipe - 8, 10, 12, 16, >16 inch'), ('PUMP2S, PUMPR, PUMP1S', 'Pump (PUMP2S, PUMPR, PUMP1S)'), ('TANKBOTTOM', 'Tank620 - Bottom (TANKBOTTOM)'), ('TANKBOTEDGE', 'Tank620 - Bottom Edge (TANKBOTEDGE)'), ('COURSE-1-10', 'Tank620 - Course 1-10'), ('TANKBOTTOM', 'Tank650 - Bottom (TANKBOTTOM)'), ('TANKBOTEDGE', 'Tank650 - Bottom Edge (TANKBOTEDGE)'), ('COURSE-1-10', 'Tank650 - Course 1-10'), ('FINFAN TUBES, HEADER', 'FinFan (Tubes, Header)'), ('Drum, Reactor, Column', 'Vessel (Drum, Reactor, Column, Filter)')], max_length=255, verbose_name='RBIX Component Type'),
        ),
        migrations.AlterField(
            model_name='component',
            name='representative_fluid',
            field=models.CharField(blank=True, choices=[('C1-C2', 'C1-C2 (Methane, ethane, ethylene, liquefied natural gas (LNG), fuel gas)'), ('C3-C4', 'C3-C4 (Propane, butane, isobutane, liquefied petroleum gas (LPG))'), ('C5', 'C5 (Pentane)'), ('C6-C8', 'C6-C8 (Gasoline, naphtha, light straight run, heptane)'), ('C9-C12', 'C9-C12 (Diesel, kerosene)'), ('C13-C16', 'C13-C16 (Jet fuel, kerosene, atmospheric gas oil)'), ('C17-C25', 'C17-C25 (Gas oil, typical crude)'), ('C25+', 'C25+ (Residuum, heavy crude, lube oil, seal oil)'), ('H2', 'H2 (Hydrogen)'), ('H2S', 'H2S (Hydrogen sulfide)'), ('HF', 'HF (Hydrogen fluoride)'), ('HCl', 'HCl (Hydrochloric acid)'), ('Water', 'Water (Water)'), ('Steam', 'Steam (Steam)'), ('Acid', 'Acid (Acid, caustic)'), ('Aromatics', 'Aromatics (Benzene, toluene, xylene, cumene)'), ('AlCl3', 'AlCl3 (Aluminum chloride)'), ('Pyrophoric', 'Pyrophoric (Pyrophoric materials)'), ('Ammonia', 'Ammonia (Ammonia)'), ('Chlorine', 'Chlorine (Chlorine)'), ('CO', 'CO (Carbon monoxide)'), ('DEE', 'DEE (Diethyl ether)'), ('Nitric acid', 'Nitric acid (Nitric acid)'), ('NO2', 'NO2 (Nitrogen dioxide)'), ('Phosgene', 'Phosgene (Phosgene)'), ('TDI', 'TDI (Toluene diisocyanate)'), ('Methanol', 'Methanol (Methanol)'), ('PO', 'PO (Propylene oxide)'), ('Styrene', 'Styrene (Styrene)'), ('EEA', 'EEA (Ethylene glycol monoethyl ether acetate)'), ('EE', 'EE (Ethylene glycol monoethyl ether)'), ('EG', 'EG (Ethylene glycol)'), ('EO', 'EO (Ethylene oxide)')], max_length=255, null=True, verbose_name='Representative Fluid'),
        ),
    ]
