# Generated by Django 6.0.1 on 2026-01-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_component_component_type_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='atm_pressure_liquid',
            new_name='atm_pressure',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='discharge_coeff_liquid',
            new_name='discharge_coeff',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='storage_pressure_liquid',
            new_name='storage_pressure',
        ),
        migrations.RemoveField(
            model_name='component',
            name='atm_pressure_vapor',
        ),
        migrations.RemoveField(
            model_name='component',
            name='discharge_coeff_vapor',
        ),
        migrations.RemoveField(
            model_name='component',
            name='storage_pressure_vapor',
        ),
    ]
