# Generated by Django 6.0.1 on 2026-01-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_atm_pressure_liquid_component_atm_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='material_construction',
            field=models.CharField(blank=True, choices=[('Carbon Steel', 'Carbon Steel (Factor: 1.0)'), ('Organic coatings (<80 mil)', 'Organic coatings (<80 mil) (Factor: 1.2)'), ('1.25Cr-0.5Mo', '1.25Cr-0.5Mo (Factor: 1.3)'), ('2.25Cr-1Mo', '2.25Cr-1Mo (Factor: 1.7)'), ('5Cr-0.5Mo', '5Cr-0.5Mo (Factor: 1.7)'), ('7Cr-0.5Mo', '7Cr-0.5Mo (Factor: 2.0)'), ('Clad 304 SS', 'Clad 304 SS (Factor: 2.1)'), ('Fiberglass', 'Fiberglass (Factor: 2.5)'), ('PP lined', 'PP lined (Factor: 2.5)'), ('9Cr-1Mo', '9Cr-1Mo (Factor: 2.6)'), ('405 SS', '405 SS (Factor: 2.8)'), ('410 SS', '410 SS (Factor: 2.8)'), ('304 SS', '304 SS (Factor: 3.2)'), ('Clad 316 SS', 'Clad 316 SS (Factor: 3.3)'), ('Strip lined alloy', 'Strip lined alloy (Factor: 3.3)'), ('Organic coating (>80 mil)', 'Organic coating (>80 mil) (Factor: 3.4)'), ('CS saran lined', 'CS saran lined (Factor: 3.4)'), ('CS rubber lined', 'CS rubber lined (Factor: 4.4)'), ('316 SS', '316 SS (Factor: 4.8)'), ('CS glass lined', 'CS glass lined (Factor: 5.8)'), ('Clad Alloy 400', 'Clad Alloy 400 (Factor: 6.4)'), ('90/10 Cu/Ni', '90/10 Cu/Ni (Factor: 6.8)'), ('Clad Alloy 600', 'Clad Alloy 600 (Factor: 7.0)'), ('CS PTFE lined', 'CS PTFE lined (Factor: 7.8)'), ('Clad nickel', 'Clad nickel (Factor: 8.0)'), ('Alloy 800', 'Alloy 800 (Factor: 8.4)'), ('70/30 Cu/Ni', '70/30 Cu/Ni (Factor: 8.5)'), ('904L', '904L (Factor: 8.8)'), ('Alloy 20', 'Alloy 20 (Factor: 11)'), ('Alloy 400', 'Alloy 400 (Factor: 15)'), ('Alloy 600', 'Alloy 600 (Factor: 15)'), ('Nickel', 'Nickel (Factor: 18)'), ('Acid brick', 'Acid brick (Factor: 20)'), ('Refractory', 'Refractory (Factor: 20)'), ('Alloy 625', 'Alloy 625 (Factor: 26)'), ('Titanium', 'Titanium (Factor: 28)'), ('Alloy C', 'Alloy C (Factor: 29)'), ('Zirconium', 'Zirconium (Factor: 34)'), ('Alloy B', 'Alloy B (Factor: 36)'), ('Tantalum', 'Tantalum (Factor: 535)')], max_length=255, null=True, verbose_name='Material of Construction'),
        ),
    ]
