# Generated by Django 6.0.1 on 2026-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_component_material_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='allowable_stress_psi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Allowable Stress (psi)'),
        ),
        migrations.AddField(
            model_name='component',
            name='atmosphere_corrosivity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=255, null=True, verbose_name='Atmosphere Corrosivity'),
        ),
        migrations.AddField(
            model_name='component',
            name='design_code',
            field=models.CharField(blank=True, choices=[('ASME VIII Div 1', 'ASME VIII Div 1'), ('ASME VIII Div 2', 'ASME VIII Div 2'), ('API 650', 'API 650')], max_length=255, null=True, verbose_name='Design Code'),
        ),
        migrations.AddField(
            model_name='component',
            name='design_pressure_psi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Design Pressure (psi)'),
        ),
        migrations.AddField(
            model_name='component',
            name='design_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Design Temp. (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='diameter_inside_in',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Inside Diameter (inch)'),
        ),
        migrations.AddField(
            model_name='component',
            name='diameter_outside_in',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Outside Diameter (inch)'),
        ),
        migrations.AddField(
            model_name='component',
            name='heat_traced',
            field=models.BooleanField(default=False, verbose_name='Heat Traced'),
        ),
        migrations.AddField(
            model_name='component',
            name='insulated',
            field=models.BooleanField(default=False, verbose_name='Insulated'),
        ),
        migrations.AddField(
            model_name='component',
            name='insulation_type',
            field=models.CharField(blank=True, choices=[('Calcium Silicate', 'Calcium Silicate'), ('Mineral Wool', 'Mineral Wool'), ('Fiberglass', 'Fiberglass'), ('Foam Glass', 'Foam Glass'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Insulation Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='internal_cladding',
            field=models.BooleanField(default=False, verbose_name='Internal Cladding'),
        ),
        migrations.AddField(
            model_name='component',
            name='internal_lining',
            field=models.BooleanField(default=False, verbose_name='Internal Lining'),
        ),
        migrations.AddField(
            model_name='component',
            name='joint_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True, verbose_name='Joint Efficiency'),
        ),
        migrations.AddField(
            model_name='component',
            name='material_nominal_composition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material Nominal Composition'),
        ),
        migrations.AddField(
            model_name='component',
            name='material_specification_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material Specification No'),
        ),
        migrations.AddField(
            model_name='component',
            name='mdmt_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MDMT (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='nominal_thickness_in',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='NT (inch)'),
        ),
        migrations.AddField(
            model_name='component',
            name='nominal_thickness_known',
            field=models.BooleanField(default=False, verbose_name='Nominal Thickness Known'),
        ),
        migrations.AddField(
            model_name='component',
            name='other_insulation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Insulation'),
        ),
        migrations.AddField(
            model_name='component',
            name='pfd_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PFD No'),
        ),
        migrations.AddField(
            model_name='component',
            name='pwht',
            field=models.BooleanField(default=False, verbose_name='PWHT'),
        ),
        migrations.AddField(
            model_name='component',
            name='safety_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Safety Factor'),
        ),
        migrations.AddField(
            model_name='component',
            name='size_diameter_rating',
            field=models.CharField(blank=True, choices=[('Under 20', 'Under 20'), ('Over 20', 'Over 20')], max_length=255, null=True, verbose_name='Size Diameter Rating'),
        ),
        migrations.AddField(
            model_name='component',
            name='smys_yield_psi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SMYS (Yield) (psi)'),
        ),
        migrations.AddField(
            model_name='component',
            name='stress_strength_known',
            field=models.BooleanField(default=False, verbose_name='Stress / Strength Known'),
        ),
        migrations.AddField(
            model_name='component',
            name='sulphur_bearing_compounds',
            field=models.BooleanField(default=False, verbose_name='Sulphur Bearing Compounds'),
        ),
    ]
