# Generated by Django 6.0.1 on 2026-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_component_allowable_stress_psi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_fluid_mass_lb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Component Fluid Mass (lb)'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_group_fluid_mass_lb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Component Group Fluid Mass (lb)'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_may_operate_below_mdmt',
            field=models.BooleanField(default=False, verbose_name='Component may operate at or below the MDMT'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_amine',
            field=models.BooleanField(default=False, verbose_name='Amine'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_chloride',
            field=models.BooleanField(default=False, verbose_name='Chloride'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_co2',
            field=models.BooleanField(default=False, verbose_name='CO₂'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_h2s',
            field=models.BooleanField(default=False, verbose_name='H₂S'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_h2so4',
            field=models.BooleanField(default=False, verbose_name='H₂SO₄'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_hcl',
            field=models.BooleanField(default=False, verbose_name='HCl'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_hf',
            field=models.BooleanField(default=False, verbose_name='HF'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_oxygen',
            field=models.BooleanField(default=False, verbose_name='Oxygen'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_sulphur',
            field=models.BooleanField(default=False, verbose_name='Sulphur'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_water',
            field=models.BooleanField(default=False, verbose_name='Water'),
        ),
        migrations.AddField(
            model_name='component',
            name='fire_reduction_safety_effectiveness',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True, verbose_name='Fire Reduction Safety Systems Effectiveness'),
        ),
        migrations.AddField(
            model_name='component',
            name='flow_velocity_fts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flow Velocity (ft/s)'),
        ),
        migrations.AddField(
            model_name='component',
            name='fluid_description',
            field=models.TextField(blank=True, null=True, verbose_name='Fluid Description'),
        ),
        migrations.AddField(
            model_name='component',
            name='fluid_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fluid Name'),
        ),
        migrations.AddField(
            model_name='component',
            name='fluid_release_reduction_safety_effectiveness',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True, verbose_name='Fluid Release Reduction Safety Systems Effectiveness'),
        ),
        migrations.AddField(
            model_name='component',
            name='inhibitor_efficiency_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Inhibitor Efficiency (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='operating_pressure_psia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Operating Pressure (psia)'),
        ),
        migrations.AddField(
            model_name='component',
            name='operating_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Operating Temperature (deg F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='operational_fluid_phase',
            field=models.CharField(blank=True, choices=[('Gas', 'Gas'), ('Liquid', 'Liquid'), ('Two-Phase', 'Two-Phase')], max_length=50, null=True, verbose_name='Operational Fluid Phase'),
        ),
        migrations.AddField(
            model_name='component',
            name='ph_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='component',
            name='rbix_fluid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RBIX Fluid'),
        ),
    ]
