# Generated by Django 6.0.1 on 2026-01-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_component_component_fluid_mass_lb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='alcl3_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='AlCl₃, Aluminum Chloride (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='c2h4o3_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='C₂H₄O₃, Ethylene Oxide (EO) (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='c3h6o2_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='C₃H₆O₂, Propylene Oxide (PO) (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='c3h8o2_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='C₃H₈O₂, Ethylene Glycol Monomethyl Ether (EE) (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='co2_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='CO₂ Carbon Monoxide (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='cocl2_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='COCl₂, Phosphine (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_caustic',
            field=models.BooleanField(default=False, verbose_name='Caustic'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_hydrogen',
            field=models.BooleanField(default=False, verbose_name='Hydrogen'),
        ),
        migrations.AddField(
            model_name='component',
            name='contains_oil',
            field=models.BooleanField(default=False, verbose_name='Oil'),
        ),
        migrations.AddField(
            model_name='component',
            name='cooling_water_service',
            field=models.BooleanField(default=False, verbose_name='Cooling Water Service'),
        ),
        migrations.AddField(
            model_name='component',
            name='h2o2_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='H₂O₂, Nitrogen Dioxide (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='h2s_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='H₂S (Hydrogen sulfide)(W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='high_hydrogen_partial_pressure',
            field=models.BooleanField(default=False, verbose_name='Hydrogen partial pressure > 0.032 MPa [50 psi]'),
        ),
        migrations.AddField(
            model_name='component',
            name='hno3_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='HNO₃, Nitric Acid (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='nh3_concentration_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='NH₃, Ammonia (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='toluene_diisocynate_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Toluene Diisocynate (TDI) (W%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='toxic_mass_fraction_wpercent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Toxic Mass Fraction'),
        ),
        migrations.AddField(
            model_name='component',
            name='underground',
            field=models.BooleanField(default=False, verbose_name='Underground'),
        ),
    ]
