# Generated by Django 6.0.1 on 2026-01-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_component_alcl3_concentration_wpercent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='corrosion_rate_mm_year',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Corrosion Rate (mm/year)'),
        ),
        migrations.AddField(
            model_name='component',
            name='ext_inspection_vol_mil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='External Inspection (vol, Mil)'),
        ),
        migrations.AddField(
            model_name='component',
            name='external_coating_quality',
            field=models.CharField(blank=True, choices=[('', '-- Select Quality --'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=50, null=True, verbose_name='External Coating Quality'),
        ),
        migrations.AddField(
            model_name='component',
            name='external_corrosion_finding_capability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], max_length=50, null=True, verbose_name='External Corrosion Finding Capability'),
        ),
        migrations.AddField(
            model_name='component',
            name='external_crack_finding_capability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True, verbose_name='External Crack Finding Capability'),
        ),
        migrations.AddField(
            model_name='component',
            name='inspection_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Inspection Summary'),
        ),
        migrations.AddField(
            model_name='component',
            name='int_inspection_vol_mil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Int. Inspection (vol, Mil)'),
        ),
        migrations.AddField(
            model_name='component',
            name='internal_corrosion_finding_capability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], max_length=50, null=True, verbose_name='Internal Corrosion Finding Capability'),
        ),
        migrations.AddField(
            model_name='component',
            name='internal_crack_finding_capability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True, verbose_name='Internal Crack Finding Capability'),
        ),
        migrations.AddField(
            model_name='component',
            name='internal_cracks_present',
            field=models.BooleanField(default=False, verbose_name='Internal Cracks Present'),
        ),
        migrations.AddField(
            model_name='component',
            name='internal_lining_quality',
            field=models.CharField(blank=True, choices=[('', '-- Select Quality --'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=50, null=True, verbose_name='Internal Lining Quality'),
        ),
        migrations.AddField(
            model_name='component',
            name='last_ext_visual_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Ext. Visual Inspection Date'),
        ),
        migrations.AddField(
            model_name='component',
            name='last_int_visual_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Int. Visual Inspection Date'),
        ),
        migrations.AddField(
            model_name='component',
            name='service_years_since_last_ext_visual_insp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Years Since Last Ext. Visual Insp.'),
        ),
        migrations.AddField(
            model_name='component',
            name='service_years_since_last_int_visual_insp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Years Since Last Int. Visual Insp.'),
        ),
        migrations.AddField(
            model_name='component',
            name='thickness_measured_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Measured Thickness (mm)'),
        ),
        migrations.AddField(
            model_name='component',
            name='thickness_minimum_required_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Required Thickness (mm)'),
        ),
        migrations.AddField(
            model_name='component',
            name='thickness_nominal_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nominal Thickness (mm)'),
        ),
        migrations.CreateModel(
            name='InspectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('Internal Visual', 'Internal Visual'), ('External Visual', 'External Visual')], max_length=20, verbose_name='Method')),
                ('date', models.DateField(verbose_name='Date')),
                ('lining_quality', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Average', 'Average')], max_length=50, null=True, verbose_name='Lining Quality')),
                ('general_condition', models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Average', 'Average')], max_length=50, verbose_name='General Condition')),
                ('crack_finding_capability', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, verbose_name='Crack Finding Capability')),
                ('corrosion_finding_capability', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], max_length=50, verbose_name='Corrosion Finding Capability')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_history', to='dashboard.component')),
            ],
            options={
                'verbose_name': 'Inspection History',
                'verbose_name_plural': 'Inspection Histories',
                'ordering': ['-date'],
            },
        ),
    ]
