# Generated by Django 6.0.1 on 2026-01-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_component_rbix_fluid'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='brittle_admin_controls',
            field=models.BooleanField(default=False, verbose_name='Admin Controls Prevent Pressurization?'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_cet_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Critical Exposure Temp (CET) (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_delta_fatt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delta FATT'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_min_operating_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min. Operating Temp (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_pwht',
            field=models.BooleanField(default=False, verbose_name='PWHT (Brittle Specific)'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_brittle_fracture_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Brittle Fracture'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_external_damage_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: External Damage'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_caustic_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: SCC Caustic'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='Caustic Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='Caustic Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (Caustic)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (Caustic)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (Caustic)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (Caustic)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_naoh_conc_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='NaOH Concentration (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_steamed_out_prior',
            field=models.BooleanField(default=False, verbose_name='Steamed Out Prior to Service?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_caustic_stress_relieved',
            field=models.BooleanField(default=False, verbose_name='Caustic Stress Relieved?'),
        ),
    ]
