# Generated by Django 6.0.1 on 2026-01-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_component_brittle_admin_controls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='brittle_delta_fatt',
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_exemption_curve',
            field=models.CharField(blank=True, choices=[('Curve A', 'Curve A'), ('Curve B', 'Curve B'), ('Curve C', 'Curve C'), ('Curve D', 'Curve D')], max_length=10, null=True, verbose_name='Exemption Curve'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_fse',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Service Experience Factor (FSE)'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_inspection_factor',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True, verbose_name='Inspection Factor'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_material_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Material Type (Brittle)'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_service_life_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Life (years)'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_tref_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Reference Temp (Tref) (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_yield_strength_ksi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yield Strength (ksi)'),
        ),
        migrations.AddField(
            model_name='component',
            name='emb885_ferrite_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ferrite Content (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='emb885_max_op_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Op Temp (°F) (885)'),
        ),
        migrations.AddField(
            model_name='component',
            name='emb885_min_op_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Op Temp (°F) (885)'),
        ),
        migrations.AddField(
            model_name='component',
            name='emb885_service_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Years (885)'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_885f_embrittlement_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: 885°F Embrittlement'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_sigma_phase_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Sigma Phase'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_temper_embrittlement_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Temper Embrittlement'),
        ),
        migrations.AddField(
            model_name='component',
            name='sigma_cr_equiv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cr Equivalent'),
        ),
        migrations.AddField(
            model_name='component',
            name='sigma_max_op_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Op Temp (°F) (Sigma)'),
        ),
        migrations.AddField(
            model_name='component',
            name='sigma_min_op_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Op Temp (°F) (Sigma)'),
        ),
        migrations.AddField(
            model_name='component',
            name='sigma_ni_equiv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ni Equivalent'),
        ),
        migrations.AddField(
            model_name='component',
            name='sigma_service_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Years (Sigma)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_admin_controls',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Admin Controls (Temper)?'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_chem_comp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chemical Composition'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_delta_fatt_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delta FATT (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_impact_test_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Impact Test Temp (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_material_screening',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Material Screening?'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_min_op_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Op Temp (°F) (Temper)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_mpt_process_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MPT by Process Engineer (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_sce_delta_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SCE Delta Temp (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_service_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Service Years (Temper)'),
        ),
        migrations.AddField(
            model_name='component',
            name='temper_tmdt_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Design Temp (TMDT) (°F)'),
        ),
        migrations.AlterField(
            model_name='component',
            name='brittle_admin_controls',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Admin Controls?'),
        ),
        migrations.AlterField(
            model_name='component',
            name='brittle_pwht',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='PWHT?'),
        ),
    ]
