# Generated by Django 6.0.1 on 2026-01-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_component_brittle_delta_fatt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='brittle_exemption_curve',
        ),
        migrations.RemoveField(
            model_name='component',
            name='brittle_fse',
        ),
        migrations.RemoveField(
            model_name='component',
            name='brittle_inspection_factor',
        ),
        migrations.RemoveField(
            model_name='component',
            name='brittle_material_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='brittle_service_life_years',
        ),
        migrations.RemoveField(
            model_name='component',
            name='brittle_tref_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='brittle_yield_strength_ksi',
        ),
        migrations.RemoveField(
            model_name='component',
            name='emb885_ferrite_percent',
        ),
        migrations.RemoveField(
            model_name='component',
            name='emb885_max_op_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='emb885_min_op_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='emb885_service_years',
        ),
        migrations.RemoveField(
            model_name='component',
            name='mechanism_885f_embrittlement_active',
        ),
        migrations.RemoveField(
            model_name='component',
            name='mechanism_sigma_phase_active',
        ),
        migrations.RemoveField(
            model_name='component',
            name='mechanism_temper_embrittlement_active',
        ),
        migrations.RemoveField(
            model_name='component',
            name='sigma_cr_equiv',
        ),
        migrations.RemoveField(
            model_name='component',
            name='sigma_max_op_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='sigma_min_op_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='sigma_ni_equiv',
        ),
        migrations.RemoveField(
            model_name='component',
            name='sigma_service_years',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_admin_controls',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_chem_comp',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_delta_fatt_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_impact_test_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_material_screening',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_min_op_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_mpt_process_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_sce_delta_temp_f',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_service_years',
        ),
        migrations.RemoveField(
            model_name='component',
            name='temper_tmdt_f',
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_delta_fatt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delta FATT'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_acscc_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: ACSCC'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_amine_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: SCC Amine'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_clscc_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: ClSCC'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_hic_h2s_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: HIC/SOHIC-H2S'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_hsc_hf_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: HSC-HF'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_pascc_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: PASCC'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_scc_ssc_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: SSC'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_co3_conc_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CO3 Concentration (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='ACSCC Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='ACSCC Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (ACSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (ACSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (ACSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (ACSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_acscc_stress_relieved',
            field=models.BooleanField(default=False, verbose_name='ACSCC Stress Relieved?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='Amine Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='Amine Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (Amine)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (Amine)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (Amine)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (Amine)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_solution_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Amine Solution Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_steamed_out',
            field=models.BooleanField(default=False, verbose_name='Amine Steamed Out?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_amine_stress_relieved',
            field=models.BooleanField(default=False, verbose_name='Amine Stress Relieved?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_cl_conc_ppm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cl Concentration (ppm)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='ClSCC Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='ClSCC Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (ClSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (ClSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (ClSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_clscc_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (ClSCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_banding_severity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Banding Severity'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='HIC Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='HIC Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_cyanide_present',
            field=models.BooleanField(default=False, verbose_name='Cyanide Present?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_h2s_ppm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2S (ppm) (HIC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (HIC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (HIC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (HIC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (HIC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hic_h2s_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH (HIC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='HSC-HF Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='HSC-HF Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_hardness_hrc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hardness (HRC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_hf_conc_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='HF Concentration (%)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (HSC-HF)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (HSC-HF)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (HSC-HF)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (HSC-HF)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='PASCC Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='PASCC Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (PASCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (PASCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (PASCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (PASCC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_sensitized',
            field=models.BooleanField(default=False, verbose_name='Material Sensitized?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_pascc_sulfur_exposure',
            field=models.BooleanField(default=False, verbose_name='Sulfur Exposure?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_cracks_observed',
            field=models.BooleanField(default=False, verbose_name='SSC Cracks Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_cracks_removed',
            field=models.BooleanField(default=False, verbose_name='SSC Cracks Removed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_h2s_ppm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2S Content (ppm)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_hardness_hb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Max Hardness (HB)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_inspection_count_a',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat A (SSC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_inspection_count_b',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat B (SSC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_inspection_count_c',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat C (SSC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_inspection_count_d',
            field=models.IntegerField(default=0, verbose_name='Insp. Count Cat D (SSC)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_ssc_pwht',
            field=models.BooleanField(default=False, verbose_name='SSC PWHT?'),
        ),
        migrations.AlterField(
            model_name='component',
            name='brittle_admin_controls',
            field=models.BooleanField(default=False, verbose_name='Admin Controls Prevent Pressurization?'),
        ),
        migrations.AlterField(
            model_name='component',
            name='brittle_pwht',
            field=models.BooleanField(default=False, verbose_name='PWHT (Brittle Specific)'),
        ),
    ]
