# Generated by Django 6.0.1 on 2026-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_component_brittle_exemption_curve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='material_construction',
            field=models.CharField(blank=True, choices=[('CS', 'Carbon Steel'), ('304SS', '304 Stainless Steel'), ('316SS', '316 Stainless Steel'), ('Alloy400', 'Alloy 400 (Monel)'), ('Alloy625', 'Alloy 625 (Inconel)'), ('Alloy825', 'Alloy 825 (Incoloy)'), ('AL', 'Aluminum'), ('CuNi', 'Copper-Nickel'), ('Titanium', 'Titanium'), ('FiberglassRTR', 'Fiberglass (RTR)'), ('PVC', 'PVC Lined'), ('RubberLined', 'Rubber Lined'), ('GlassLined', 'Glass Lined'), ('DuplexSS', 'Duplex Stainless Steel'), ('SuperDuplexSS', 'Super Duplex Stainless Steel')], max_length=255, null=True, verbose_name='Material of Construction'),
        ),
    ]
