# Generated by Django 6.0.1 on 2026-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_component_material_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='material_construction',
            field=models.CharField(blank=True, choices=[('Carbon Steel', 'Carbon Steel'), ('Organic coatings (< 80 mil)', 'Organic coatings (< 80 mil)'), ('1.25Cr-0.5Mo', '1.25Cr-0.5Mo'), ('2.25Cr-1Mo', '2.25Cr-1Mo'), ('5Cr-0.5Mo', '5Cr-0.5Mo'), ('7Cr-0.5Mo', '7Cr-0.5Mo'), ('Clad 304 SS', 'Clad 304 SS'), ('Fiberglass', 'Fiberglass'), ('PP lined', 'PP lined'), ('9Cr-1Mo', '9Cr-1Mo'), ('405 SS', '405 SS'), ('410 SS', '410 SS'), ('304 SS', '304 SS'), ('Clad 316 SS', 'Clad 316 SS'), ('Strip lined alloy', 'Strip lined alloy'), ('Organic coating (> 80 mil)', 'Organic coating (> 80 mil)'), ('CS saran lined', 'CS saran lined'), ('CS rubber lined', 'CS rubber lined'), ('316 SS', '316 SS'), ('CS glass lined', 'CS glass lined'), ('Clad Alloy 400', 'Clad Alloy 400'), ('90/10 Cu/Ni', '90/10 Cu/Ni'), ('Clad Alloy 600', 'Clad Alloy 600'), ('CS PTFE lined', 'CS PTFE lined'), ('Clad nickel', 'Clad nickel'), ('Alloy 800', 'Alloy 800'), ('70/30 Cu/Ni', '70/30 Cu/Ni'), ('904L', '904L'), ('Alloy 20', 'Alloy 20'), ('Alloy 400', 'Alloy 400'), ('Alloy 600', 'Alloy 600'), ('Nickel', 'Nickel'), ('Acid brick', 'Acid brick'), ('Refractory', 'Refractory'), ('Alloy 625', 'Alloy 625'), ('Titanium', 'Titanium'), ('Alloy C', 'Alloy C'), ('Zirconium', 'Zirconium'), ('Alloy B', 'Alloy B'), ('Tantalum', 'Tantalum')], max_length=255, null=True, verbose_name='Material of Construction'),
        ),
    ]
