# Generated by Django 6.0.1 on 2026-01-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_component_material_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='scc_amine_solution_type',
            field=models.CharField(blank=True, choices=[('MEA_DIPA', 'MEA or DIPA'), ('DEA_OTHER', 'DEA or Others')], max_length=20, null=True, verbose_name='Amine Solution Type'),
        ),
    ]
