# Generated by Django 6.0.1 on 2026-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_component_scc_amine_solution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='scc_amine_lean_amine',
            field=models.BooleanField(default=False, verbose_name='Exposed to Lean Amine?'),
        ),
    ]
