# Generated by Django 6.0.1 on 2026-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_component_scc_amine_lean_amine'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='scc_pascc_downtime_protected',
            field=models.BooleanField(default=False, verbose_name='Downtime Protection Used?'),
        ),
        migrations.AlterField(
            model_name='component',
            name='scc_hic_h2s_banding_severity',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='None', max_length=20, verbose_name='Banding Severity'),
        ),
    ]
