# Generated by Django 6.0.1 on 2026-01-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_component_scc_pascc_downtime_protected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='scc_clscc_deposits_present',
            field=models.BooleanField(default=False, verbose_name='Deposits Present?'),
        ),
    ]
