# Generated by Django 6.0.1 on 2026-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_component_scc_clscc_deposits_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='scc_hsc_hf_hardness_hrc',
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_hardness_hb',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Hardness (HB)'),
        ),
        migrations.AddField(
            model_name='component',
            name='scc_hsc_hf_present',
            field=models.BooleanField(default=False, verbose_name='HF Present?'),
        ),
    ]
