# Generated by Django 6.0.1 on 2026-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_component_scc_hsc_hf_hardness_hrc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mech_thinning_acid_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Acid Water Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_alkaline_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Alkaline Water Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_amine_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Amine Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_co2_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: CO2 Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_h2s_h2_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: High Temp H2S/H2'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_h2so4_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: H2SO4 Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_hcl_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: HCl Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_hf_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: HF Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_soil_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Soil Side Corrosion'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_thinning_sulfidic_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: Sulfidic/Naphthenic'),
        ),
    ]
