# Generated by Django 6.0.1 on 2026-01-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_component_mech_thinning_acid_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='co2_concentration_mol_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CO2 Concentration (mol %)'),
        ),
        migrations.AddField(
            model_name='component',
            name='co2_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CO2 Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='co2_shear_stress_pa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shear Stress (Pa)'),
        ),
    ]
