# Generated by Django 6.0.1 on 2026-01-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_component_co2_concentration_mol_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='future_corrosion_allowance_in',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.125, help_text='FCA per API 570. Typical: 0.125" (1/8") for moderate service, 0.250" (1/4") for severe.', max_digits=6, null=True, verbose_name='Future Corrosion Allowance (in)'),
        ),
        migrations.AddField(
            model_name='component',
            name='min_required_thickness_in',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Per ASME design calculation (t_min). If unknown, leave blank for simplified DF calculation.', max_digits=6, null=True, verbose_name='Minimum Required Thickness (in)'),
        ),
        migrations.AlterField(
            model_name='component',
            name='co2_shear_stress_pa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CO2 Shear Stress (Pa)'),
        ),
    ]
