# Generated by Django 6.0.1 on 2026-01-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_component_future_corrosion_allowance_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='acid_water_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acid Water CR (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='acid_water_dissolved_o2_ppm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dissolved O2 (ppm)'),
        ),
        migrations.AddField(
            model_name='component',
            name='alkaline_water_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alkaline Water CR (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='alkaline_water_velocity_fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alkaline Water Velocity (ft/s)'),
        ),
        migrations.AddField(
            model_name='component',
            name='amine_acid_gas_loading',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Acid Gas Loading (mol/mol)'),
        ),
        migrations.AddField(
            model_name='component',
            name='amine_concentration_wt_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Amine Concentration (wt %)'),
        ),
        migrations.AddField(
            model_name='component',
            name='amine_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amine Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='amine_type',
            field=models.CharField(blank=True, choices=[('MEA', 'Monoethanolamine (MEA)'), ('DEA', 'Diethanolamine (DEA)'), ('MDEA', 'Methyldiethanolamine (MDEA)'), ('DGA', 'Diglycolamine (DGA)')], max_length=10, null=True, verbose_name='Amine Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='h2so4_concentration_wt_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='H2SO4 Concentration (wt %)'),
        ),
        migrations.AddField(
            model_name='component',
            name='h2so4_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2SO4 Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='h2so4_velocity_fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='H2SO4 Velocity (ft/s)'),
        ),
        migrations.AddField(
            model_name='component',
            name='hcl_concentration_wt_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='HCl Concentration (wt %)'),
        ),
        migrations.AddField(
            model_name='component',
            name='hcl_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HCl Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='hcl_velocity_fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HCl Velocity (ft/s)'),
        ),
        migrations.AddField(
            model_name='component',
            name='hf_concentration_wt_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='HF Concentration (wt %)'),
        ),
        migrations.AddField(
            model_name='component',
            name='hf_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HF Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='hf_velocity_fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HF Velocity (ft/s)'),
        ),
        migrations.AddField(
            model_name='component',
            name='ht_h2_partial_pressure_psia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2 Partial Pressure (psia)'),
        ),
        migrations.AddField(
            model_name='component',
            name='ht_h2s_h2_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HT H2S/H2 CR (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='ht_h2s_partial_pressure_psia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2S Partial Pressure (psia)'),
        ),
        migrations.AddField(
            model_name='component',
            name='soil_cathodic_protection',
            field=models.BooleanField(default=False, verbose_name='Cathodic Protection Active'),
        ),
        migrations.AddField(
            model_name='component',
            name='soil_coating_condition',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('NONE', 'No Coating')], max_length=10, null=True, verbose_name='Coating Condition'),
        ),
        migrations.AddField(
            model_name='component',
            name='soil_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Soil Side CR (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='soil_resistivity_ohm_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Soil Resistivity (ohm-cm)'),
        ),
        migrations.AddField(
            model_name='component',
            name='sulfidic_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sulfidic CR (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='sulfidic_sulfur_wt_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sulfur Content (wt %)'),
        ),
        migrations.AddField(
            model_name='component',
            name='sulfidic_tan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='TAN (Total Acid Number)'),
        ),
        migrations.AddField(
            model_name='component',
            name='sulfidic_velocity_fps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Velocity (ft/s)'),
        ),
    ]
