# Generated by Django 6.0.1 on 2026-01-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_component_acid_water_corrosion_rate_mpy_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "acid_water_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "acid_water_dissolved_o2_ppm" numeric(8, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "alkaline_water_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "alkaline_water_velocity_fps" numeric(8, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "amine_acid_gas_loading" numeric(6, 3) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "amine_concentration_wt_percent" numeric(6, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "amine_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "amine_type" varchar(10) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "h2so4_concentration_wt_percent" numeric(6, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "h2so4_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "h2so4_velocity_fps" numeric(8, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "hcl_concentration_wt_percent" numeric(6, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "hcl_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "hcl_velocity_fps" numeric(8, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "hf_concentration_wt_percent" numeric(6, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "hf_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "hf_velocity_fps" numeric(8, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "ht_h2_partial_pressure_psia" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "ht_h2s_h2_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "ht_h2s_partial_pressure_psia" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "soil_cathodic_protection" boolean NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "soil_coating_condition" varchar(10) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "soil_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "soil_resistivity_ohm_cm" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "sulfid ic_corrosion_rate_mpy" numeric(10, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "sulfidic_sulfur_wt_percent" numeric(6, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "sulfidic_tan" numeric(6, 2) NULL;
            ALTER TABLE "dashboard_component" ADD COLUMN IF NOT EXISTS "sulfidic_velocity_fps" numeric(8, 2) NULL;
            -- Set default for soil_cathodic_protection to false for existing rows
            UPDATE "dashboard_component" SET "soil_cathodic_protection" = false WHERE "soil_cathodic_protection" IS NULL;
            -- Make soil_cathodic_protection NOT NULL after setting default
            ALTER TABLE "dashboard_component" ALTER COLUMN "soil_cathodic_protection" SET DEFAULT false;
            ALTER TABLE "dashboard_component" ALTER COLUMN "soil_cathodic_protection" SET NOT NULL;
            """,
            reverse_sql="-- No reverse needed"
        ),
    ]
