# Generated by Django 6.0.1 on 2026-01-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_add_thinning_columns'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "dashboard_component" RENAME COLUMN "sulfid ic_corrosion_rate_mpy" TO "sulfidic_corrosion_rate_mpy";',
            reverse_sql='ALTER TABLE "dashboard_component" RENAME COLUMN "sulfidic_corrosion_rate_mpy" TO "sulfid ic_corrosion_rate_mpy";'
        ),
    ]
