# Generated by Django 6.0.1 on 2026-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_fix_sulfidic_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='complexity',
            field=models.CharField(blank=True, choices=[('High', 'High (Pipe, <1.5" OD)'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True, verbose_name='Complexity'),
        ),
        migrations.AddField(
            model_name='component',
            name='cui_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CUI Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='cui_driver',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50, null=True, verbose_name='CUI Driver'),
        ),
        migrations.AddField(
            model_name='component',
            name='external_corrosion_rate_mpy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='External Corrosion Rate (mpy)'),
        ),
        migrations.AddField(
            model_name='component',
            name='external_driver',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Marine', 'Marine'), ('Temperate', 'Temperate'), ('Arid/Dry', 'Arid/Dry'), ('Severe', 'Severe')], max_length=50, null=True, verbose_name='External Corrosion Driver'),
        ),
        migrations.AddField(
            model_name='component',
            name='insulation_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=50, null=True, verbose_name='Insulation Condition'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_cui_active',
            field=models.BooleanField(default=False, verbose_name='CUI Active'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_cui_clscc_active',
            field=models.BooleanField(default=False, verbose_name='CUI ClSCC Active'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_ext_clscc_active',
            field=models.BooleanField(default=False, verbose_name='External ClSCC Active'),
        ),
        migrations.AddField(
            model_name='component',
            name='mech_ext_corrosion_active',
            field=models.BooleanField(default=False, verbose_name='External Corrosion Active'),
        ),
    ]
