# Generated by Django 6.0.1 on 2026-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_add_external_damage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='brittle_damage_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brittle Fracture DF'),
        ),
    ]
