# Generated by Django 6.0.1 on 2026-01-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_component_brittle_damage_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='brittle_curve',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Exemption Curve'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_material_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Material Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='brittle_yield_strength_ksi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yield Strength (ksi)'),
        ),
    ]
