# Generated by Django 6.0.1 on 2026-01-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_component_brittle_curve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='htha_damage_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HTHA Damage Factor'),
        ),
        migrations.AddField(
            model_name='component',
            name='htha_damage_observed',
            field=models.BooleanField(default=False, verbose_name='HTHA Damage Observed?'),
        ),
        migrations.AddField(
            model_name='component',
            name='htha_exposure_time_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HTHA Exposure Time (years)'),
        ),
        migrations.AddField(
            model_name='component',
            name='htha_h2_partial_pressure_psia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='H2 Partial Pressure (psia)'),
        ),
        migrations.AddField(
            model_name='component',
            name='htha_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HTHA Material'),
        ),
        migrations.AddField(
            model_name='component',
            name='htha_material_verification',
            field=models.BooleanField(default=False, verbose_name='HTHA Material Verification Done?'),
        ),
        migrations.AddField(
            model_name='component',
            name='htha_temp_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='HTHA Operating Temp (°F)'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanism_htha_active',
            field=models.BooleanField(default=False, verbose_name='Mech. Active: HTHA'),
        ),
    ]
