# Generated by Django 6.0.1 on 2026-02-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_component_htha_damage_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='htha_temp_f',
        ),
    ]
