# Generated by Django 6.0.1 on 2026-02-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_htha_temp_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='final_pof',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Final POF (failures/year)'),
        ),
        migrations.AddField(
            model_name='component',
            name='fms_factor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='FMS Factor'),
        ),
        migrations.AddField(
            model_name='component',
            name='fms_pscore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='FMS P-Score'),
        ),
        migrations.AddField(
            model_name='component',
            name='gff_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Generic Failure Frequency'),
        ),
        migrations.AddField(
            model_name='component',
            name='pof_category',
            field=models.IntegerField(blank=True, null=True, verbose_name='POF Category (1-5)'),
        ),
    ]
