# Generated by Django 6.0.1 on 2026-02-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_add_pof_gff_fms_fields'),
        ('formula_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='gff_component_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_components', to='formula_app.componenttype', verbose_name='GFF Component Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='gff_equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_components', to='formula_app.equipmenttype', verbose_name='GFF Equipment Type'),
        ),
    ]
