# Generated by Django 6.0.1 on 2026-02-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_add_gff_equipment_component_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='calculated_cof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Calculated Financial COF ($)'),
        ),
        migrations.AddField(
            model_name='component',
            name='calculated_consequence_area',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Calculated Consequence Area (m2)'),
        ),
        migrations.AddField(
            model_name='component',
            name='calculated_risk',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Calculated Risk (m2/yr)'),
        ),
        migrations.AddField(
            model_name='component',
            name='calculated_total_damage_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Calculated Total DF'),
        ),
    ]
