# Generated by Django 6.0.1 on 2026-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_component_calculated_cof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='cof_category',
            field=models.CharField(blank=True, choices=[('A', 'A - Negligible'), ('B', 'B - Minor'), ('C', 'C - Moderate'), ('D', 'D - Major'), ('E', 'E - Catastrophic')], max_length=1, null=True, verbose_name='COF Category (A-E)'),
        ),
    ]
