# Generated by Django 5.2.7 on 2025-11-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Premium'),
        ),
    ]
